# Generated by Django 5.1.5 on 2025-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.TextField()),
                ('AcceptingCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingPerson',
            fields=[
                ('RatingPersonID', models.AutoField(primary_key=True, serialize=False)),
                ('BehavioralRank', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('AcademicRank', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('RatingID', models.AutoField(primary_key=True, serialize=False)),
                ('BehavioralRank', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AcademicRank', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Comments', models.TextField()),
            ],
        ),
    ]
