# Generated by Django 5.1.5 on 2025-02-12 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rating', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingperson',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='Audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Audience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='Commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
