# Generated by Django 5.1.5 on 2025-05-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_answer',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_public',
        ),
    ]
