# Generated by Django 5.1.5 on 2025-05-13 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0005_rename_post_responsetopoic_topic_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseTopoic',
            new_name='ResponseTopic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
        migrations.CreateModel(
            name='TopicMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Topics.topic')),
            ],
        ),
    ]
