# Generated by Django 5.1.5 on 2025-02-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_alter_proposal_course'),
        ('complaint_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.course'),
        ),
    ]
