# Generated by Django 5.1.5 on 2025-02-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_ticket', '0002_complaint_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
