# Generated by Django 5.1.5 on 2025-04-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
