# Generated by Django 5.1.5 on 2025-02-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
    ]
