# Generated by Django 5.1.5 on 2025-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField(auto_now_add=True)),
                ('EndTime', models.DateTimeField(auto_now=True)),
                ('ClassLink', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['-StartTime'],
            },
        ),
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waiting', 'Waiting')], default='waiting', max_length=100)),
                ('CountClass', models.IntegerField(default=1)),
                ('SuggestedTime', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Class Requests',
                'ordering': ['-SuggestedTime'],
            },
        ),
        migrations.CreateModel(
            name='ListMyClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staus', models.CharField(choices=[('past', 'برگزارشده'), ('Wait', 'در انتظار پذیرفتن'), ('accept', 'پذیرفته شده')], default='waiting', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='waitingHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
