# Generated by Django 5.1.5 on 2025-05-01 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinvitation',
            name='code_Creator',
            field=models.CharField(default='code_123', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinvitation',
            name='code_teacher',
            field=models.CharField(default='code_123', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinvitation',
            name='creator_name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinvitation',
            name='teacher_name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
