# Generated by Django 5.1.5 on 2025-02-12 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tags', '0001_initial'),
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='Acceptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='Calling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calling', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='Requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Tags.category'),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='Tags.tag'),
        ),
        migrations.AddField(
            model_name='course',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_detail', to='classroom.courserequest'),
        ),
        migrations.AddField(
            model_name='listmyclasses',
            name='MyCource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myclasses', to='classroom.courserequest'),
        ),
        migrations.AddField(
            model_name='waitinghall',
            name='ClassRequest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waititent', to='classroom.courserequest'),
        ),
        migrations.AddField(
            model_name='waitinghall',
            name='Proposers',
            field=models.ManyToManyField(blank=True, related_name='proposed_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
