# Generated by Django 5.1.5 on 2025-05-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_courseinvitation_code_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinvitation',
            name='Course_name',
            field=models.CharField(db_index=True, default='test', max_length=200),
            preserve_default=False,
        ),
    ]
