# Generated by Django 5.1.5 on 2025-02-12 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
        ('classroom', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequest',
            name='Acceptor',
        ),
        migrations.AddField(
            model_name='course',
            name='Acceepter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Accepted', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='Status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='waiting', max_length=100),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='Title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='courses', to='Tags.tag'),
        ),
        migrations.AlterField(
            model_name='waitinghall',
            name='Proposers',
            field=models.ManyToManyField(related_name='proposed_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
