# Generated by Django 5.1.5 on 2025-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_courserequest_acceptor_course_acceepter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmyclasses',
            name='Staus',
            field=models.CharField(choices=[('past', 'برگزارشده'), ('Wait', 'در انتظار پذیرفتن'), ('accept', 'پذیرفته شده')], default='Wait', max_length=100),
        ),
    ]
