# Generated by Django 5.1.5 on 2025-05-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_courseinvitation_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequestcourse',
            name='course_name',
            field=models.CharField(db_index=True, default='math', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalrequestcourse',
            name='user_proposal_name',
            field=models.CharField(default='ariya', max_length=200),
            preserve_default=False,
        ),
    ]
