# Generated by Django 5.1.5 on 2025-02-13 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
        ('classroom', '0005_remove_waitinghall_proposers_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-lastCreateTime'], 'verbose_name_plural': 'Courses'},
        ),
        migrations.RenameField(
            model_name='courserequest',
            old_name='Requester',
            new_name='Creator',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Acceepter',
        ),
        migrations.RemoveField(
            model_name='course',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='course',
            name='StartTime',
        ),
        migrations.RemoveField(
            model_name='courserequest',
            name='Status',
        ),
        migrations.AddField(
            model_name='course',
            name='lastCreateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courserequest',
            name='acceptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال انتظار '), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='pending', max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='ClassLink',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='SuggestedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='Tags.tag'),
        ),
        migrations.CreateModel(
            name='CourseInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='classroom.courserequest')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListCourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MyCource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myclasses', to='classroom.courseinvitation')),
            ],
        ),
        migrations.DeleteModel(
            name='ListMyClasses',
        ),
    ]
