# Generated by Django 5.1.5 on 2025-02-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_remove_courserequest_acceptor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeCourse',
        ),
    ]
