# Generated by Django 5.1.5 on 2025-02-14 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_delete_timecourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.courserequest'),
        ),
    ]
