# Generated by Django 5.1.5 on 2025-02-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
        ('classroom', '0011_coursecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreate',
            name='CountClass',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coursecreate',
            name='SuggestedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecreate',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coursesCreate', to='Tags.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecreate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='coursesCreate', to='Tags.tag'),
        ),
    ]
