# Generated by Django 5.1.5 on 2025-02-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_coursecreate_countclass_coursecreate_suggestedtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecreate',
            old_name='Calling',
            new_name='inviteUser',
        ),
        migrations.RenameField(
            model_name='courserequest',
            old_name='Calling',
            new_name='inviteUser',
        ),
    ]
