# Generated by Django 5.1.5 on 2025-02-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_rename_calling_coursecreate_inviteuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecreate',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='courserequest',
            name='tags',
        ),
        migrations.AddField(
            model_name='coursecreate',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='classroom/images/'),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='classroom/images/'),
        ),
    ]
