# Generated by Django 5.1.5 on 2025-02-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_remove_coursecreate_tags_remove_courserequest_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/courseImages'),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/courseImages'),
        ),
    ]
