# Generated by Django 5.1.5 on 2025-02-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_alter_coursecreate_images_alter_courserequest_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='SuggestedTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='SuggestedTime',
            field=models.DateTimeField(),
        ),
    ]
