# Generated by Django 5.1.5 on 2025-02-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_alter_coursecreate_suggestedtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecreate',
            name='inviteUser',
        ),
        migrations.RemoveField(
            model_name='courserequest',
            name='inviteUser',
        ),
        migrations.AddField(
            model_name='courserequest',
            name='LinkAccess',
            field=models.CharField(default='15fd8da6-28a1-440c', max_length=18, unique=True),
        ),
    ]
