# Generated by Django 5.1.5 on 2025-02-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_remove_coursecreate_inviteuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='4dc8ae67-9ee9-4f8c', max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='LinkAccess',
            field=models.CharField(default='f760509d-ba95-400d', max_length=18, unique=True),
        ),
    ]
