# Generated by Django 5.1.5 on 2025-02-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_coursecreate_linkaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='43c22505-b669-4', max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='LinkAccess',
            field=models.CharField(default='2f185b81-a809-4', max_length=18, unique=True),
        ),
    ]
