# Generated by Django 5.1.5 on 2025-02-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_alter_coursecreate_linkaccess_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecreate',
            name='applicants',
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='409ee0ea-0f18-4', max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='LinkAccess',
            field=models.CharField(default='fc7f4548-5863-4', max_length=18, unique=True),
        ),
    ]
