# Generated by Django 5.1.5 on 2025-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_remove_coursecreate_applicants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserequest',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='courserequest',
            name='images',
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='196cbec2-3c71-4', max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='LinkAccess',
            field=models.CharField(default='27701813-d490-4', max_length=18, unique=True),
        ),
    ]
