# Generated by Django 5.1.5 on 2025-02-25 14:27

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_alter_coursecreate_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='f56f20f7-5b48-4', max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='LinkAccess',
            field=models.CharField(default=classroom.models.generate_unique_link, max_length=18, unique=True),
        ),
    ]
