# Generated by Django 5.1.5 on 2025-02-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0023_alter_coursecreate_linkaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='5dda38e0-6f7d-4', max_length=18, unique=True),
        ),
    ]
