# Generated by Django 5.1.5 on 2025-02-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0024_alter_coursecreate_linkaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='4bcee803-8d0b-4', max_length=18, unique=True),
        ),
    ]
