# Generated by Django 5.1.5 on 2025-02-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0025_alter_coursecreate_linkaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='447d12ac-40f3-4', max_length=18, unique=True),
        ),
    ]
