# Generated by Django 5.1.5 on 2025-02-25 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0026_coursecreate_is_active_courserequest_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcourse',
            name='Attendees',
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='Students',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='e4235aeb-adff-4', max_length=18, unique=True),
        ),
    ]
