# Generated by Django 5.1.5 on 2025-02-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0027_remove_groupcourse_attendees_groupcourse_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreate',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='b081f3c0-4424-4', max_length=18, unique=True),
        ),
    ]
