# Generated by Django 5.1.5 on 2025-02-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0028_coursecreate_is_private_courserequest_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinghall',
            name='Title',
            field=models.CharField(db_index=True, default='Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitinghall',
            name='description',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='316ce606-0f77-4', max_length=18, unique=True),
        ),
    ]
