# Generated by Django 5.1.5 on 2025-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0029_waitinghall_title_waitinghall_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='CodeCreator',
            field=models.CharField(default='f8162e1b-0eb', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courserequest',
            name='username',
            field=models.CharField(default='ariya', max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='d3b5c702-1677-4', max_length=18, unique=True),
        ),
    ]
