# Generated by Django 5.1.5 on 2025-02-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0030_courserequest_codecreator_courserequest_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='92eaf8ed-e9ae-4', max_length=18, unique=True),
        ),
    ]
