# Generated by Django 5.1.5 on 2025-02-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0032_courseinvitation_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinvitation',
            name='description',
            field=models.TextField(default='test for description '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='e7ade3cd-6101-4', max_length=18, unique=True),
        ),
    ]
