# Generated by Django 5.1.5 on 2025-02-28 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0033_courseinvitation_description_and_more'),
        ('complaint_ticket', '0003_delete_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Proposals'},
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='is_agreement',
            new_name='agreement_price',
        ),
        migrations.AddField(
            model_name='coursecreate',
            name='CapacityCourse',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='99cdb560-9770-4', max_length=18, unique=True),
        ),
        migrations.CreateModel(
            name='AgreementCourseCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('ClassLink', models.CharField(max_length=500)),
                ('isHeld', models.BooleanField(default=False)),
                ('createCourse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='createCourse', to='classroom.coursecreate')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ['-Time'],
            },
        ),
        migrations.CreateModel(
            name='AgreementCourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('ClassLink', models.CharField(max_length=500)),
                ('isHeld', models.BooleanField(default=False)),
                ('requestCourse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requestCourse', to='classroom.courserequest')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ['-Time'],
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
