# Generated by Django 5.1.5 on 2025-03-01 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0034_alter_proposal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposal',
            new_name='ProposalRequestCourse',
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='c3287621-c83a-4', max_length=18, unique=True),
        ),
        migrations.CreateModel(
            name='ProposalCreateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'در حال انتظار '), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='pending', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.coursecreate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
