# Generated by Django 5.1.5 on 2025-03-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0035_rename_proposal_proposalrequestcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinvitation',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalcreatecourse',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalrequestcourse',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='2206f270-5753-4', max_length=18, unique=True),
        ),
    ]
