# Generated by Django 5.1.5 on 2025-03-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0036_courseinvitation_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementcourserequest',
            name='ClassLink',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agreementcourserequest',
            name='Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='a2637d8b-82c1-4', max_length=18, unique=True),
        ),
    ]
