# Generated by Django 5.1.5 on 2025-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0037_alter_agreementcourserequest_classlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='99401380-95b0-4', max_length=18, unique=True),
        ),
    ]
