# Generated by Django 5.1.5 on 2025-03-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0038_alter_coursecreate_linkaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementcourserequest',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='401cfdaf-7f2a-4', max_length=18, unique=True),
        ),
    ]
