# Generated by Django 5.1.5 on 2025-03-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0039_agreementcourserequest_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='249caef1-a882-4', max_length=18, unique=True),
        ),
    ]
