# Generated by Django 5.1.5 on 2025-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0040_alter_coursecreate_linkaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='d759fc0f-7672-4', max_length=18, unique=True),
        ),
    ]
