# Generated by Django 5.1.5 on 2025-03-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0041_alter_coursecreate_linkaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='1d579113-8d74-4', max_length=18, unique=True),
        ),
        migrations.DeleteModel(
            name='ListCourseRequest',
        ),
    ]
