# Generated by Django 5.1.5 on 2025-03-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0042_alter_coursecreate_linkaccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementcoursecreate',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='c5380686-f368-4', max_length=18, unique=True),
        ),
    ]
