# Generated by Django 5.1.5 on 2025-03-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0043_agreementcoursecreate_average_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementcoursecreate',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_attention', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementcoursecreate',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachercourse', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreementcourserequest',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementcourserequest',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_invent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreementcoursecreate',
            name='createCourse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_create', to='classroom.coursecreate'),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='1caa7993-4d37-4', max_length=18, unique=True),
        ),
        migrations.DeleteModel(
            name='GroupCourse',
        ),
    ]
