# Generated by Django 5.1.5 on 2025-03-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0044_agreementcoursecreate_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreementcoursecreate',
            old_name='isHeld',
            new_name='is_Held',
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='be617ed9-3912-4', max_length=18, unique=True),
        ),
    ]
