# Generated by Django 5.1.5 on 2025-03-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0045_rename_isheld_agreementcoursecreate_is_held_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='5cc34644-e567-4', max_length=18, unique=True),
        ),
    ]
