# Generated by Django 5.1.5 on 2025-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0046_alter_coursecreate_linkaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='aabf158c-dd53-4', max_length=18, unique=True),
        ),
    ]
