# Generated by Django 5.1.5 on 2025-03-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0049_alter_coursecreate_linkaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecreate',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='adca48c9-bfdd-4', max_length=18, unique=True),
        ),
    ]
