# Generated by Django 5.1.5 on 2025-03-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0050_remove_coursecreate_is_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequest',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='a0ac5f02-fdcb-4', max_length=18, unique=True),
        ),
    ]
