# Generated by Django 5.1.5 on 2025-03-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0051_remove_courserequest_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequest',
            name='is_private',
        ),
        migrations.AddField(
            model_name='courserequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default='d61d8b7b-4e7f-4', max_length=18, unique=True),
        ),
    ]
