# Generated by Django 5.1.5 on 2025-03-04 12:56

import classroom.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0052_remove_courserequest_is_private_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementcoursecreate',
            options={'ordering': ['-Time'], 'verbose_name_plural': 'Agrement Course Create'},
        ),
        migrations.AlterModelOptions(
            name='agreementcourserequest',
            options={'ordering': ['-Time'], 'verbose_name_plural': 'Agreement Course Requests'},
        ),
        migrations.RemoveField(
            model_name='waitinghall',
            name='ClassRequest',
        ),
        migrations.AddField(
            model_name='waitinghall',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitinghall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitinghall',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='LinkAccess',
            field=models.CharField(default=classroom.models.generate_unique_link, max_length=18, unique=True),
        ),
    ]
