# Generated by Django 5.1.5 on 2025-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0053_alter_agreementcoursecreate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementcoursecreate',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agreementcourserequest',
            name='Suggested_price',
            field=models.FloatField(default=0),
        ),
    ]
