# Generated by Django 5.1.5 on 2025-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0054_agreementcoursecreate_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreementcoursecreate',
            old_name='price',
            new_name='Suggested_price',
        ),
        migrations.AddField(
            model_name='waitinghall',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
