# Generated by Django 5.1.5 on 2025-03-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0055_rename_price_agreementcoursecreate_suggested_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreementcoursecreate',
            old_name='Suggested_price',
            new_name='agreement_price',
        ),
        migrations.RenameField(
            model_name='agreementcourserequest',
            old_name='Suggested_price',
            new_name='agreement_price',
        ),
        migrations.AlterField(
            model_name='agreementcourserequest',
            name='ClassLink',
            field=models.CharField(max_length=500),
        ),
    ]
