# Generated by Django 5.1.5 on 2025-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0056_rename_suggested_price_agreementcoursecreate_agreement_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreate',
            name='initial_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='initial_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
