# Generated by Django 5.1.5 on 2025-03-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0057_coursecreate_initial_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreate',
            name='CodeCreator',
            field=models.CharField(default='4fc148a4-9f6', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecreate',
            name='username',
            field=models.CharField(default='abolfazl', max_length=18),
            preserve_default=False,
        ),
    ]
