# Generated by Django 5.1.5 on 2025-03-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0058_coursecreate_codecreator_coursecreate_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserequest',
            old_name='initial_price',
            new_name='price_course',
        ),
        migrations.RemoveField(
            model_name='agreementcoursecreate',
            name='agreement_price',
        ),
        migrations.RemoveField(
            model_name='agreementcourserequest',
            name='agreement_price',
        ),
    ]
