# Generated by Django 5.1.5 on 2025-03-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0059_rename_initial_price_courserequest_price_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecreate',
            old_name='initial_price',
            new_name='price_course',
        ),
    ]
