# Generated by Django 5.1.5 on 2025-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0060_rename_initial_price_coursecreate_price_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinghall',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
