# Generated by Django 5.1.5 on 2025-03-22 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0062_waitinghall_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='waitinghall',
            name='CodeCreator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CodeCreator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitinghall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/waitingHallImages'),
        ),
    ]
