# Generated by Django 5.1.5 on 2025-03-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0063_courserequest_images_waitinghall_codecreator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinghall',
            name='CodeCreator',
            field=models.CharField(max_length=18),
        ),
    ]
