# Generated by Django 5.1.5 on 2025-03-22 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0064_alter_waitinghall_codecreator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementcourserequest',
            name='students',
        ),
        migrations.AddField(
            model_name='agreementcourserequest',
            name='Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_classRequest', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecreate',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursecreate',
            name='level_course',
            field=models.IntegerField(choices=[(1, 'elementary'), (3, 'intermediate'), (5, 'advanced')], default=1),
        ),
        migrations.AddField(
            model_name='coursecreate',
            name='teacher_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='level_course',
            field=models.IntegerField(choices=[(1, 'elementary'), (3, 'intermediate'), (5, 'advanced')], default=1),
        ),
    ]
