# Generated by Django 5.1.5 on 2025-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0065_remove_agreementcourserequest_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinghall',
            name='type_course',
            field=models.CharField(default='courserequest', max_length=500),
            preserve_default=False,
        ),
    ]
