# Generated by Django 5.1.5 on 2025-03-27 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0067_alter_proposalrequestcourse_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalrequestcourse',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Proposals_Request'},
        ),
        migrations.RenameField(
            model_name='agreementcourserequest',
            old_name='Creator',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='proposalrequestcourse',
            old_name='user',
            new_name='user_proposal',
        ),
        migrations.RemoveField(
            model_name='agreementcoursecreate',
            name='ClassLink',
        ),
        migrations.RemoveField(
            model_name='agreementcoursecreate',
            name='is_Held',
        ),
        migrations.RemoveField(
            model_name='agreementcourserequest',
            name='ClassLink',
        ),
        migrations.RemoveField(
            model_name='agreementcourserequest',
            name='isHeld',
        ),
        migrations.AddField(
            model_name='proposalrequestcourse',
            name='Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreementcoursecreate',
            name='students',
            field=models.ManyToManyField(related_name='students_attention', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreementcoursecreate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreementcourserequest',
            name='Time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proposalrequestcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_Request', to='classroom.courserequest'),
        ),
    ]
