# Generated by Django 5.1.5 on 2025-03-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0068_alter_proposalrequestcourse_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalrequestcourse',
            old_name='course',
            new_name='course_request',
        ),
    ]
