# Generated by Django 5.1.5 on 2025-02-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='NationalCode',
        ),
    ]
