# Generated by Django 5.1.5 on 2025-04-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='7be06876-229', max_length=12, unique=True),
        ),
    ]
