# Generated by Django 5.1.5 on 2025-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0002_remove_customuser_nationalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='NationalCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
