# Generated by Django 5.1.5 on 2025-04-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0002_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformationuser',
            name='skills',
            field=models.ManyToManyField(related_name='user_skill', through='user_custom.UserSkill', to='user_custom.skills'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='8ce53750-44e', max_length=12, unique=True),
        ),
    ]
