# Generated by Django 5.1.5 on 2025-04-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0003_alter_additionalinformationuser_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('NowBusy', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='additionalinformationuser',
            old_name='job',
            new_name='job_now',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='4c9cd653-baa', max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CareerHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_custom.careerhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_custom.additionalinformationuser')),
            ],
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='CareerHistory',
            field=models.ManyToManyField(related_name='career_history', through='user_custom.UserJob', to='user_custom.careerhistory'),
        ),
    ]
