# Generated by Django 5.1.5 on 2025-02-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0003_customuser_nationalcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='NationalCode',
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='NationalCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
