# Generated by Django 5.1.5 on 2025-04-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0004_careerhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='careerhistory',
            name='JobTitle',
        ),
        migrations.AddField(
            model_name='careerhistory',
            name='user_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_custom.additionalinformationuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='b12c4cf4-a18', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='careerhistory',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_custom.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionalinformationuser',
            name='CareerHistory',
            field=models.ManyToManyField(related_name='career_history', through='user_custom.CareerHistory', to='user_custom.job'),
        ),
        migrations.AlterField(
            model_name='additionalinformationuser',
            name='job_now',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_custom.job'),
        ),
        migrations.DeleteModel(
            name='UserJob',
        ),
    ]
