# Generated by Django 5.1.5 on 2025-02-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0005_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='f8162e1b-0eb', max_length=12, unique=True),
        ),
    ]
