# Generated by Django 5.1.5 on 2025-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0006_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinformationuser',
            name='first_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='last_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='c96c5d02-7c6', max_length=12, unique=True),
        ),
    ]
