# Generated by Django 5.1.5 on 2025-02-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0006_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='c2b81954-170', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user_log', 'User'), ('employee', 'Employee'), ('admin', 'Admin')], default='user_log', max_length=10),
        ),
    ]
