# Generated by Django 5.1.5 on 2025-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0007_additionalinformationuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='4c922d21-244', max_length=12, unique=True),
        ),
    ]
