# Generated by Django 5.1.5 on 2025-02-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0007_alter_customuser_codeuser_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='1090c77d-a3d', max_length=12, unique=True),
        ),
    ]
