# Generated by Django 5.1.5 on 2025-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0008_userskill_title_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='f9e4bb0e-596', max_length=12, unique=True),
        ),
    ]
