# Generated by Django 5.1.5 on 2025-02-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0008_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='bd6382a0-2f7', max_length=12, unique=True),
        ),
    ]
