# Generated by Django 5.1.5 on 2025-02-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0009_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='633c7c54-6ac', max_length=12, unique=True),
        ),
    ]
