# Generated by Django 5.1.5 on 2025-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0009_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='title',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='2eed6880-629', max_length=12, unique=True),
        ),
    ]
