# Generated by Django 5.1.5 on 2025-04-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0010_remove_userskill_title_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='1657f8e5-d53', max_length=12, unique=True),
        ),
    ]
