# Generated by Django 5.1.5 on 2025-02-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0010_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='d659338c-8da', max_length=12, unique=True),
        ),
    ]
