# Generated by Django 5.1.5 on 2025-05-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0012_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='2c669d87-0d1', max_length=12, unique=True),
        ),
    ]
