# Generated by Django 5.1.5 on 2025-02-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0013_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='37be5305-b50', max_length=12, unique=True),
        ),
    ]
