# Generated by Django 5.1.5 on 2025-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0013_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='428af3e0-f1e', max_length=12, unique=True),
        ),
    ]
