# Generated by Django 5.1.5 on 2025-02-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0015_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='59a6c75d-53e', max_length=12, unique=True),
        ),
    ]
