# Generated by Django 5.1.5 on 2025-05-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0015_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='52a81045-90b', max_length=12, unique=True),
        ),
    ]
