# Generated by Django 5.1.5 on 2025-05-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0016_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='c74ce2a5-376', max_length=12, unique=True),
        ),
    ]
