# Generated by Django 5.1.5 on 2025-02-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0016_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='df35e859-572', max_length=12, unique=True),
        ),
    ]
