# Generated by Django 5.1.5 on 2025-05-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0017_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='6bb3b0df-429', max_length=12, unique=True),
        ),
    ]
