# Generated by Django 5.1.5 on 2025-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0017_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='3656885d-78d', max_length=12, unique=True),
        ),
    ]
