# Generated by Django 5.1.5 on 2025-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0018_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='d170a8b0-403', max_length=12, unique=True),
        ),
    ]
