# Generated by Django 5.1.5 on 2025-03-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0019_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='8f0269a1-802', max_length=12, unique=True),
        ),
    ]
