# Generated by Django 5.1.5 on 2025-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0019_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='10bc36ad-b7b', max_length=12, unique=True),
        ),
    ]
