# Generated by Django 5.1.5 on 2025-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0020_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='5fef4c14-06a', max_length=12, unique=True),
        ),
    ]
