# Generated by Django 5.1.5 on 2025-05-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0021_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='15dc0906-37d', max_length=12, unique=True),
        ),
    ]
