# Generated by Django 5.1.5 on 2025-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0021_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='3e558ac6-85c', max_length=12, unique=True),
        ),
    ]
