# Generated by Django 5.1.5 on 2025-03-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0022_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='ef3f08ff-9fb', max_length=12, unique=True),
        ),
    ]
