# Generated by Django 5.1.5 on 2025-03-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0023_customuser_average_rating_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='4f566a56-2fc', max_length=12, unique=True),
        ),
    ]
