# Generated by Django 5.1.5 on 2025-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0024_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='277109da-2c7', max_length=12, unique=True),
        ),
    ]
