# Generated by Django 5.1.5 on 2025-03-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0025_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='b9a956aa-68c', max_length=12, unique=True),
        ),
    ]
