# Generated by Django 5.1.5 on 2025-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0026_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='71afc8cd-1e1', max_length=12, unique=True),
        ),
    ]
