# Generated by Django 5.1.5 on 2025-03-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0027_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='44fb150b-381', max_length=12, unique=True),
        ),
    ]
