# Generated by Django 5.1.5 on 2025-03-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0028_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='9ed912eb-d71', max_length=12, unique=True),
        ),
    ]
