# Generated by Django 5.1.5 on 2025-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0029_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='184ccd92-11c', max_length=12, unique=True),
        ),
    ]
