# Generated by Django 5.1.5 on 2025-03-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0030_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='771fa928-b64', max_length=12, unique=True),
        ),
    ]
