# Generated by Django 5.1.5 on 2025-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0031_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='e9cc035c-f87', max_length=12, unique=True),
        ),
    ]
