# Generated by Django 5.1.5 on 2025-04-07 12:41

import cama.upload_paths
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0032_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='address_line',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد '), ('female', 'زن')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=cama.upload_paths.profile_image_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='38221765-848', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_custom.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='user_custom.province'),
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_custom.province'),
        ),
    ]
