# Generated by Django 5.1.5 on 2025-04-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0033_city_province_additionalinformationuser_address_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='e5598a64-a2c', max_length=12, unique=True),
        ),
    ]
