# Generated by Django 5.1.5 on 2025-04-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0034_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='7561425e-75f', max_length=12, unique=True),
        ),
    ]
