# Generated by Django 5.1.5 on 2025-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0035_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='840d817b-6e2', max_length=12, unique=True),
        ),
    ]
