# Generated by Django 5.1.5 on 2025-04-10 11:41

import cama.upload_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0036_alter_customuser_codeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformationuser',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinformationuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=cama.upload_paths.profile_image_path),
        ),
        migrations.AlterField(
            model_name='additionalinformationuser',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_custom.skills'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='60823717-25c', max_length=12, unique=True),
        ),
    ]
