# Generated by Django 5.1.5 on 2025-04-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0037_alter_additionalinformationuser_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinformationuser',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='9401f2fa-81e', max_length=12, unique=True),
        ),
    ]
