# Generated by Django 5.1.5 on 2025-04-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0038_rename_birthday_additionalinformationuser_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinformationuser',
            name='NationalCode',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='77bfe669-155', max_length=12, unique=True),
        ),
    ]
