# Generated by Django 5.1.5 on 2025-04-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0039_remove_additionalinformationuser_nationalcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinformationuser',
            name='skills',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codeUser',
            field=models.CharField(default='5201e11d-dd1', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='additionalinformationuser',
            name='skills',
            field=models.ManyToManyField(to='user_custom.skills'),
        ),
    ]
